/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AppClass.sm
 */

package com.bluecc.ws.charts.fixtures.ex1;


public class AppClassContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public AppClassContext(AppClass owner)
    {
        this (owner, Map1.Start);
    }

    public AppClassContext(AppClass owner, AppClassState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void EOS()
    {
        _transition = "EOS";
        getState().EOS(this);
        _transition = "";
        return;
    }

    public void One()
    {
        _transition = "One";
        getState().One(this);
        _transition = "";
        return;
    }

    public void Unknown()
    {
        _transition = "Unknown";
        getState().Unknown(this);
        _transition = "";
        return;
    }

    public void Zero()
    {
        _transition = "Zero";
        getState().Zero(this);
        _transition = "";
        return;
    }

    public AppClassState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((AppClassState) _state);
    }

    protected AppClass getOwner()
    {
        return (_owner);
    }

    public void setOwner(AppClass owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private AppClass _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class AppClassState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AppClassState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(AppClassContext context) {}
        protected void exit(AppClassContext context) {}

        protected void EOS(AppClassContext context)
        {
            Default(context);
        }

        protected void One(AppClassContext context)
        {
            Default(context);
        }

        protected void Unknown(AppClassContext context)
        {
            Default(context);
        }

        protected void Zero(AppClassContext context)
        {
            Default(context);
        }

        protected void Default(AppClassContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class Map1
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final Map1_Start Start =
            new Map1_Start("Map1.Start", 0);
        public static final Map1_Zeros Zeros =
            new Map1_Zeros("Map1.Zeros", 1);
        public static final Map1_Ones Ones =
            new Map1_Ones("Map1.Ones", 2);
        public static final Map1_OK OK =
            new Map1_OK("Map1.OK", 3);
        public static final Map1_Error Error =
            new Map1_Error("Map1.Error", 4);
    }

    protected static class Map1_Default
        extends AppClassState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Map1_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Map1_Start
        extends Map1_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Map1_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void EOS(AppClassContext context)
        {
            AppClass ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.Acceptable();
            }
            finally
            {
                context.setState(Map1.OK);
                (context.getState()).entry(context);
            }


            return;
        }

        @Override
        protected void One(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Ones);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Unknown(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Error);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Zero(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Zeros);
            (context.getState()).entry(context);

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Map1_Zeros
        extends Map1_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Map1_Zeros(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void EOS(AppClassContext context)
        {
            AppClass ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.Acceptable();
            }
            finally
            {
                context.setState(Map1.OK);
                (context.getState()).entry(context);
            }


            return;
        }

        @Override
        protected void One(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Ones);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Unknown(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Error);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Zero(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Zeros);
            (context.getState()).entry(context);

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Map1_Ones
        extends Map1_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Map1_Ones(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void EOS(AppClassContext context)
        {
            AppClass ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.Acceptable();
            }
            finally
            {
                context.setState(Map1.OK);
                (context.getState()).entry(context);
            }


            return;
        }

        @Override
        protected void One(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Ones);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Unknown(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Error);
            (context.getState()).entry(context);

            return;
        }

        @Override
        protected void Zero(AppClassContext context)
        {

            (context.getState()).exit(context);
            context.setState(Map1.Error);
            (context.getState()).entry(context);

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Map1_OK
        extends Map1_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Map1_OK(String name, int id)
        {
            super (name, id);
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Map1_Error
        extends Map1_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Map1_Error(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void EOS(AppClassContext context)
        {
            AppClass ctxt = context.getOwner();

            AppClassState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.Unacceptable();
            }
            finally
            {
                context.setState(endState);
            }


            return;
        }

        @Override
        protected void One(AppClassContext context)
        {


            return;
        }

        @Override
        protected void Unknown(AppClassContext context)
        {


            return;
        }

        @Override
        protected void Zero(AppClassContext context)
        {


            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
