build:
    ../gradlew build --exclude-task test --warning-mode none
srv:
	../gradlew run -PchooseMain=com.bluecc.ws.charts.SimpleClient
charts:
    ../gradlew run -PchooseMain=com.bluecc.ws.charts.ChartServices

# $ just history "wf_id run_id"
history args:
    ../gradlew run -PchooseMain=com.bluecc.ws.charts.common.WorkflowExecutionHistoryPrinter --args="{{args}}"
file-worker:
    ../gradlew run -PchooseMain=com.bluecc.ws.charts.fixtures.fileprocessing.FileProcessingWorker
file:
    ../gradlew run -PchooseMain=com.bluecc.ws.charts.fixtures.fileprocessing.FileProcessingStarter

domain name:
	cadence --domain {{name}} domain describe
